name = "flashstream-worker"
main = "worker/worker.js"
compatibility_date = "2024-05-24" # Set to current date
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding       = "DB"  # Changed from flashstream_db to DB to match your code
database_name = "flashstream-db"
database_id   = "6da5875a-37c7-4c12-b1d3-6eeaf4ced61c"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true